// <auto-generated />
namespace MyDiary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SetFirstNameAndLastNameMaxLengthTo30InStudentsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetFirstNameAndLastNameMaxLengthTo30InStudentsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202401251418004_SetFirstNameAndLastNameMaxLengthTo30InStudentsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
